### ISSUE TITLE
How to track stream events from downloadSequence?

### ISSUE THREAD

**Issue by hansputera** [ido-pluto/ipull#10]
Hi @ido-pluto, thank you for creating this useful library to download multiple files easily.

I would like to ask how to properly use streaming events when I use the downloadSequence method? I can't track progress or completed events from 'DownloadEngineMultiDownload' (returned by downloadSequence method)

Here's my code:
![image](https://github.com/ido-pluto/ipull/assets/47862061/40f0db49-721a-4ecc-b781-6dbc7f8e56c9)

On my previous attempt, I ran the `downloader.download()` method. It runs automatically and show completed download status (when I debug `downloader.downloadStatues`), but I don't receive any progress or completed event from `downloader` / `DownloadEngineMultiDownload` class

Any solution? Thanks!

**Comment by ido-pluto** [comment]
The progress data of `downloadSequence` is the total progress of all files as a whole.
If you want to be notified when the sub-download started/finished, you can listen to `childDownloadStarted` and `childDownloadClosed`

If you want to listen to all progress but get each sub-download progress **separately**, check the data in `downloader.downloadStatues`

```js
const downloader = await downloadSequence(...)

downloader.on("progress", () => {
    console.log(downloader.downloadStatues);
});
```

**Comment by ido-pluto** [comment]
That may be related to the flag `skipExisting`, that is weird you did not get completion events (`finished` event). 
For me, the `finished` event fired even when skipping existing files.

Can you provide more context or any details that may be relevant?

**Comment by hansputera** [comment]
> That may be related to the flag `skipExisting`, that is weird you did not get completion events (`finished` event). For me, the `finished` event fired even when skipping existing files.
> 
> Can you provide more context or any details that may be relevant?

Thanks for your reply.

Here, I want to download 10 URLs (each URL on a different server), and I need to track the progress of everything in % (percentage), and it would be helpful if we could track the download speed.

So, from the documentation, we can use the `progress` event to track progress (This works for a while, and won't work anymore after the 2nd attempt), and sometimes we get stuck on a block loop when awaiting for the downloadSequence(...) method.

For the `finished` event, I've set up the debug code, we can use `console.log` or similar. And, it doesn't log anything

**Comment by ido-pluto** [comment]
Which version of Node.js are you using? Please try upgrading to the latest version.

There's a retry algorithm in place. Disable it so that any errors are thrown immediately, as this might be causing delays.
```js
downloadFile({
   ...
    retry: {
        retries: 0
    }
})

```


The `downloadSequence` gathers information about the downloads, which is why it can take some time. Maybe one of the servers is very slow, try removing some to see if one of them particularly causes delays.

Does disabling the `skipExisting` option make any difference?

The `downloadSequence` won't fire a finished event only if an error occurs. Try wrapping the downloader in a try-catch block.

If any of these suggestions help, please let me know. I want to improve ipull for future use :)
