### ISSUE TITLE
missing .node native modules

### ISSUE THREAD

**Issue by fanghtml** [ido-pluto/ipull#11]
In my project, I used ipull. When packaging the project with esbuild, I am always notified that I am missing .node native modules. I have tried to configure the handling of native modules, but it still doesn't solve the problem.

**Comment by ido-pluto** [comment]
Thanks for reporting! :)

Can you share how you bundle your project?
If you need browser support, only import from `"ipull/browser"`

```
import { downloadFileBrowser } from "ipull/browser";
```

The .node native module is imported dynamically inside a try-catch only on the Node.js imports. 
The package containing the node addon is this: https://www.npmjs.com/package/@reflink/reflink.

I tried to bundle this with Vite, and it bundled without a problem.

Check your import and ensure you do not import from  "ipull", only from "ipull/browser" on the browser.

**Comment by fanghtml** [comment]
I am currently using esbuild to bundle for Node, and it was fine with webpack before.

**Comment by ido-pluto** [comment]
There a few things you can try:
1. uninstall and reinstall the package with `--no-optional`, `npm install --no-optional ipull`
2. override `@reflink/reflink` this package with another, as this is an optional package: 
```json
{
    "overrides": {
        "ipull": {
            "@reflink/reflink": "npm:fs-extra"
        }
    }
}
```
3. Change the esbuild config to import `@reflink/reflink` as an external package (https://esbuild.github.io/api/#node-paths)

**Comment by toodury** [comment]
I believe I have encountered a similar issue.

I am developing in an Electron environment and using Electron Forge along with Vite.
During the build process, I noticed that `index.js` was not being called, and instead, `browser.js` was being loaded.

After investigating, I found that the root cause was in the `download-engine-nodejs` file.
Specifically, I was importing the `DownloadEngineOptionsNodejs` type from this file.
It seems that the `@reflink/reflink` library, which is used within `download-engine-nodejs`, caused an error during the build process, leading to `browser.js` being loaded instead.

Luckily, following the solution suggested in the [previous comment](https://github.com/ido-pluto/ipull/issues/11#issuecomment-2326568414) resolved the issue for me.
Additionally, explicitly specifying the path when importing the `DownloadEngineOptionsNodejs` type, like so:
`ipull/dist/download/download-engine/engine/download-engine-nodejs.d.ts`, also fixed the problem.

Thank you for your help!
