### ISSUE TITLE
Size twice bigger in output

### ISSUE THREAD

**Issue by coderaiser** [ido-pluto/ipull#9]
<img width="413" alt="image" src="https://github.com/ido-pluto/ipull/assets/1573141/cf772615-849a-4065-95a6-34294e03ab70">

And file `https://raw.githubusercontent.com/quick-lint/quick-lint-js/master/website/wasm/quick-lint-js.js`

Not fully downloaded, it should be `13K`:

```
-rw-r--r--    1 coderaiser  staff    13K May 10 13:32 quick-lint-js.js
```

But it is `4K`:

<img width="494" alt="image" src="https://github.com/ido-pluto/ipull/assets/1573141/8992ff0a-de9d-4d60-b9e0-834142db14fa">

**Comment by ido-pluto** [comment]
That was a combination of bugs, thank you for noticing :)

- The first bug printed twice the size in the terminal.
- The second bug used the compressed size as the absolute size of the file (on small files)
 
Thank you again, I could not have noticed that without you!

This should be fixed in the latest release 🚀

**Comment by coderaiser** [comment]
Thank you! Works good :)
